[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port 8000"
healthcheckPath = "/api/status"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[service]
name = "eai-smartcity-prototype"
env = "python"